name: Generate Posts JSON

on:
  push:
    branches:
      - main # Run the workflow when changes are pushed to the main branch
      - darkwolf1337_blog

jobs:
  generate-posts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate posts.json
      run: |
        mkdir -p docs/js
        echo "[" > docs/js/posts.json
        for file in docs/_posts/*.md; do
          title=$(grep -m 1 "title:" "$file" | sed 's/title: //')
          date=$(grep -m 1 "date:" "$file" | sed 's/date: //')
          echo "  {" >> docs/js/posts.json
          echo "    \"path\": \"${file#docs/}\"," >> docs/js/posts.json
          echo "    \"title\": \"$title\"," >> docs/js/posts.json
          echo "    \"date\": \"$date\"" >> docs/js/posts.json
          echo "  }," >> docs/js/posts.json
        done
        sed -i '$ s/,$//' docs/js/posts.json
        echo "]" >> docs/js/posts.json

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/js/posts.json
        git commit -m "Update posts.json"
        git push